[package]
name = "radiojournal-cli"
version = "0.5.1"
edition = "2024"

[dependencies]
radiojournal = { path = "../lib", features = ["local"] }
anyhow = "=1.0.100"
tokio = { version = "=1.49.0", features = ["full"] }
tracing = "=0.1.44"
tracing-subscriber = "=0.3.22"
